### ISSUE TITLE
Missing implementation for logLaunchLink option

### ISSUE THREAD

**Issue by barking-timber** [reportportal/agent-js-playwright#114]
Looks like it only exists in the [README](https://github.com/reportportal/agent-js-playwright/blob/develop/README.md?plain=1#L59). Wondering how difficult it is to implement this? I have seen it in the [agent-js-jest](https://github.com/search?q=repo%3Areportportal%2Fagent-js-jest%20logLaunchLink&type=code), unsure if it'd be more lift & shift to this project?

**Comment by AmsterGet** [comment]
Hello @barking-timber !
It accidentally got into the readme before the official publication.
The implementation is quite simple, so we plan to release it in the next release, along with a few important fixes.

**Comment by barking-timber** [comment]
Oh, that's fab! Great job everyone, I'll keep an eye on the new release!

**Comment by AmsterGet** [comment]
Hi @barking-timber !
Please check the [version 5.1.3](https://github.com/reportportal/agent-js-playwright/releases/tag/v5.1.3).

**Comment by barking-timber** [comment]
Cool, thanks!

So does it mean that with the launch UUID I can go create links like this: 
```
<rpInstance>/ui/<projectName>/launches/all/<launchUuid>
```

Seems to be working, just don't want to miss anything closer to previously mentioned `logLaunchLink` which seems to be removed for now?

**Comment by AmsterGet** [comment]
@barking-timber Yeah, you're right.

**Comment by AmsterGet** [comment]
Hi @barking-timber !
We've published a version [5.1.5](https://github.com/reportportal/agent-js-playwright/releases/tag/v5.1.5) that logs the link to RP launch by default.
Please refer [this issue](https://github.com/reportportal/agent-js-playwright/issues/125) for details.

**Comment by barking-timber** [comment]
Hi folks, just on the `logLaunchLink` can you give me a hint on how to access the link from within Playwright execution? I'm thinking of adding it to another reporter, e.g. in the Slack notification.
