### ISSUE TITLE
Test is not finished when use expect(page).toHaveScreenshot() or key --update-snapshots

### ISSUE THREAD

**Issue by Sanek0125** [reportportal/agent-js-playwright#117]
### Test setup:
    "@playwright/test": "1.32.3",
    "@reportportal/agent-js-playwright": "5.1.2",
    
### How to reproduce:
1. file example.spec.ts:
```
import { test, expect } from '@playwright/test';

test('example test', async ({ page }) => {
  await page.goto('https://playwright.dev');
  await expect(page).toHaveScreenshot();
});
```
2. Configure RP to includeTestSteps: true
3. Run test use command:
   ` npx playwright test playwright test --config playwright.e2e.config.ts `
 or
 ` npx playwright test playwright test --config playwright.e2e.config.ts --update-snapshots`
 
### Actual result:
Test & test step (expect) are still in progress, so the entire run is also not finished
<img width="700" alt="Screen 2023-08-06 в 17 22 16" src="https://github.com/reportportal/agent-js-playwright/assets/43985376/34a0f310-2835-4396-a6bb-fde52c5cfef5">
<img width="1140" alt="Screen 2023-08-06 в 17 39 00" src="https://github.com/reportportal/agent-js-playwright/assets/43985376/6ef8fe3e-5e71-43de-b9b8-2399c47cec2b">

**Comment by AmsterGet** [comment]
Hi @Sanek0125 !
Could you please check the issue with the latest version?

**Comment by AmsterGet** [comment]
Hi @Sanek0125 !
I see that you have just closed the issue.
Did the problem disappear and now everything works as expected?
