### ISSUE TITLE
[Question] is there any way to get access to the launch ID?

### ISSUE THREAD

**Issue by CosminGramada** [reportportal/agent-js-playwright#125]
Hello,

Thank you for your work on this project.

I have a question regarding the launch Uuid / ID and specifically how it can be accessed to create (and print) the link to the launch in CI/CD pipeline logs.
I saw in the documentation that there's an option in the config allowing to print output the Uuid however I'm looking to achieve something similar present in the agent-js-jest implementation, `logLaunchLink`.

Since the playwright agent doesn't have this option I was wondering whether I can access it somehow and create the URL dynamically.

**Comment by AmsterGet** [comment]
Hello @CosminGramada !
At the moment the only option available is the one you mentioned.
Next month we are going to add a `logLaunchLink` option to the playwright agent and other agents as well.
We will notify you here.
Also will adding the `logLaunchLink` option be enough for you or do you need to get the UUID for something else?
By the way you can try to extract UUID from the console output to build the URL.

**Comment by CosminGramada** [comment]
@AmsterGet 
Thank you for the reply.
Currently, `logLaunchLink` is the only use case where the UUID would be necessary. 

I can't think of any other use cases right now, but, and this is just to spark the discussion, would be possible to make it somehow available? 
Maybe have it set as an env variable? Is this even possible?

**Comment by CosminGramada** [comment]
Hello @AmsterGet !

When do you expect to have the next version released?
Is it safe to assume that it will happen in November?

Thank you!

**Comment by AmsterGet** [comment]
Hi @CosminGramada !
Now it is possible to access the RP launch link by default on test execution end 🔥
We've added the feature directly to this agent in version [5.1.5](https://github.com/reportportal/agent-js-playwright/releases/tag/v5.1.5), but it is available for old versions as well via [client-javascript 5.0.15](https://github.com/reportportal/client-javascript/releases/tag/v5.0.15) version update during `npm install`.

Let us know in case of any questions/issues.
