### ISSUE TITLE
Attach the sceenshot to report without print image to console log

### ISSUE THREAD

**Issue by ngocdd** [reportportal/agent-js-playwright#147]
Problem:
- I want to attach the screenshot to the report but I only can do that by using the logging method like the attachment below
![Xnip2024-05-25_14-41-38](https://github.com/reportportal/agent-js-playwright/assets/107824423/e3c21977-716c-450d-8480-cd9680f9b9ca)

and those methods will print the log to the console log including the image base64 and this does not necessary

Expectation:
- Having a method to attach the screenshot to report and print the log to the console log can be an option.

**Comment by AmsterGet** [comment]
Hello @ngocdd !
Please try the Playwright's native [`testInfo.attach`](https://github.com/reportportal/agent-js-playwright?tab=readme-ov-file#attachments) method.
It works through the Playwright attachments and doesn't output anything to the console.

**Comment by ngocdd** [comment]
Thanks @AmsterGet 
I saw it, but I was custom the playwright's actions like input, click ... into the new function, and then I wanted to take the screenshot for each action function I customed but I could not call `testInfor.attach` outside the `test` functions. so that is why I want to use `ReportingApi` to call it everywhere. 

I was task a look into the report agent source code, But I'm still not understand why the image can be attached to report with this following code 
```
export const sendEventToReporter = (type: string, data: any, suite?: string): void => {
  process.stdout.write(JSON.stringify({ type, data, suite }));
};
```

**Comment by AmsterGet** [comment]
@ngocdd 
The Playwright provides the only stdout dynamic output within particular test execution, so it was the fastest solution to get any data in reporter from test without introducing custom inter-process communication mechanism for that.

> I saw it, but I was custom the playwright's actions like input, click ... into the new function, and then I wanted to take the screenshot for each action function I customed but I could not call testInfor.attach outside the test functions. so that is why I want to use ReportingApi to call it everywhere.

You can try accessing the global `test` function within your custom actions, it should receive the right test context during execution, f.e.

```javascript
import { test } from '@playwright/test';

const yourFunction = () => {
   // ...
   test.info().attach('screenshot', { body, contentType: 'image/png' });
};
```

**Comment by ngocdd** [comment]
oh, I get it. It works now. Thanks so much

**Comment by ngocdd** [comment]
`Do not hesitate do give us a star ([agent](https://github.com/reportportal/agent-js-playwright) and/or [main repo](https://github.com/reportportal/reportportal))` >> yes, sure

sorry, let me reopen this ticket, cause I have another problem and need help from you with the topic of this ticket @AmsterGet 

I used a global test to take and attach the screenshot for each action, but the screenshot in the report portal does not stay according to the action, all the screenshot is shown at the end of the test logs. before that when I used `reportApi` to attach the screenshot it stayed with the Action

![image](https://github.com/reportportal/agent-js-playwright/assets/107824423/ffc3b9be-ca7d-43a4-adeb-84169de2a64a)

**Comment by ngocdd** [comment]
ah, I saw the note here

`Note: [ReportingAPI](https://github.com/reportportal/agent-js-playwright#log) methods will send attachments to ReportPortal right after their call, unlike attachments provided via testInfo.attach that will be reported only on the test item finish.`

**Comment by AmsterGet** [comment]
> ah, I saw the note here
> 
> `Note: [ReportingAPI](https://github.com/reportportal/agent-js-playwright#log) methods will send attachments to ReportPortal right after their call, unlike attachments provided via testInfo.attach that will be reported only on the test item finish.`

@ngocdd Since `testInfo.attach` is a native Playwright method, we use its information as is and add a timestamp while sending the request (on the test finish). So yes, this is a limitation at the moment. I suppose it will be fixed after introducing the inter-process communication for the whole our JS agents ecosystem, but not this year, unfortunately.

> Do not hesitate do give us a star ([agent](https://github.com/reportportal/agent-js-playwright) and/or [main repo](https://github.com/reportportal/reportportal)) >> yes, sure

❤️
