### ISSUE TITLE
Error: Request failed with status code 404

### ISSUE THREAD

**Issue by toduyemi** [reportportal/agent-js-playwright#152]
When I run `npx playwright test` following the steps in the documentation. I receive multiple iterations of this error:

```
Error: Request failed with status code 404: {"errorCode":4040,"message":"Project 'chromium' not found. Did you use correct project name?"}
URL: http://localhost:8080/api/v1/chromium/launch
method: POST
    at /Users/temi/work/spire-web-tests-playwright/node_modules/@reportportal/client-javascript/lib/rest.js:43:15
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

Failed to finish launch. Error: Request failed with status code 404: {"errorCode":4040,"message":"Project 'chromium' not found. Did you use correct project name?"}
URL: http://localhost:8080/api/v1/chromium/launch
method: POST
    at /Users/temi/work/spire-web-tests-playwright/node_modules/@reportportal/client-javascript/lib/rest.js:43:15

Failed to send log Error: Request failed with status code 404: {"errorCode":4040,"message":"Project 'chromium' not found. Did you use correct project name?"}
URL: http://localhost:8080/api/v1/chromium/launch
method: POST
    at /Users/temi/work/spire-web-tests-playwright/node_modules/@reportportal/client-javascript/lib/rest.js:43:15
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
Failed to send log Error: Request failed with status code 404: {"errorCode":4040,"message":"Project 'chromium' not found. Did you use correct project name?"}
URL: http://localhost:8080/api/v1/chromium/launch
method: POST
    at /Users/temi/work/spire-web-tests-playwright/node_modules/@reportportal/client-javascript/lib/rest.js:43:15
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
Failed to finish test. Error: Request failed with status code 404: {"errorCode":4040,"message":"Project 'chromium' not found. Did you use correct project name?"}
URL: http://localhost:8080/api/v1/chromium/launch
method: POST
    at /Users/temi/work/spire-web-tests-playwright/node_modules/@reportportal/client-javascript/lib/rest.js:43:15
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
Failed to finish suite. Error: Request failed with status code 404: {"errorCode":4040,"message":"Project 'chromium' not found. Did you use correct project name?"}
URL: http://localhost:8080/api/v1/chromium/launch
method: POST
    at /Users/temi/work/spire-web-tests-playwright/node_modules/@reportportal/client-javascript/lib/rest.js:43:15
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
Failed to finish suite. Error: Request failed with status code 404: {"errorCode":4040,"message":"Project 'chromium' not found. Did you use correct project name?"}
URL: http://localhost:8080/api/v1/chromium/launch
method: POST
    at /Users/temi/work/spire-web-tests-playwright/node_modules/@reportportal/client-javascript/lib/rest.js:43:15
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
Failed to finish suite. Error: Request failed with status code 404: {"errorCode":4040,"message":"Project 'chromium' not found. Did you use correct project name?"}
URL: http://localhost:8080/api/v1/chromium/launch
method: POST
    at /Users/temi/work/spire-web-tests-playwright/node_modules/@reportportal/client-javascript/lib/rest.js:43:15
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```
<img width="674" alt="Screenshot 2024-08-27 at 2 59 36 PM" src="https://github.com/user-attachments/assets/e81f21e3-1b5b-4348-b696-b59a925747bd">

When I refresh the launch dashboard all it shows is this:
<img width="1319" alt="Screenshot 2024-08-27 at 3 02 42 PM" src="https://github.com/user-attachments/assets/8da28271-fb10-4381-99b3-48d0771837c2">

If I click on the URL link provided in the terminal output log, I get this.
<img width="1289" alt="Screenshot 2024-08-27 at 3 03 03 PM" src="https://github.com/user-attachments/assets/61d6685f-2867-4eae-b19e-bc1a3f044964">

From what I understand the project name is arbitrary. Am I supposed to initialize the project somewhere else? Do you have documentation for thrown errors to aid in troubleshooting.

**Comment by AmsterGet** [comment]
Hello @toduyemi !
The `project` field in `rpConfig` should contain a project from ReportPortal.
Thus, it looks like there is no project with this name `chromium` in ReportPortal.
You can use a name of the personal project, which is created for each user by default
![image](https://github.com/user-attachments/assets/2d220d80-7b47-4c91-b178-ad3ea93edbee)
or create a new one on the Administration page.
For ease of filling out the configuration file, it is best to use the sample configuration from the Profile page opened from a particular project
![image](https://github.com/user-attachments/assets/1199bd66-d6f0-4b5a-9d63-4a0ad4be98bf)
![image](https://github.com/user-attachments/assets/ae0a9fd9-9c9f-46ca-90a2-b5cbb6d67d52)

Hope this helps!

**Comment by toduyemi** [comment]
Thank you! I think the documentation should be a bit more explicit about the config api. I thought it was referring to projects key in the playwright config.

**Comment by AmsterGet** [comment]
@toduyemi the documentation mentions that it should be a ReportPortal project
![image](https://github.com/user-attachments/assets/28be72ab-bd37-414c-bab5-55c3c1fc1dba)
Anyway, we'll add more details to the configuration options to make it clearer.

**Comment by toduyemi** [comment]
Ahh I see. The way I interpreted that, was, I was naming/initializing my report portal project via that property in the config api. Thank you for explaining.
