### ISSUE TITLE
Failed to finish nested step. Error: timeout of 30000ms exceeded. URL:... method: POST. Error starts randomly throwing in the middle of test execution.

### ISSUE THREAD

**Issue by toduyemi** [reportportal/agent-js-playwright#159]
Hi in the middle of a test execution, sometimes i'll start getting non-playwright errors like this. I can't find anything in the documentation. Usually if a test times out, the terminal prints a playwright error, fails the test which makes it difficult to understand why i'm getting this weird report portal exception about timeouts.  If I click the link(s), it tells me I'm not authorized to view page.

"@playwright/test": "^1.47.2",
"@reportportal/agent-js-playwright": "^5.1.9",

The test execution always starts of normally but somewhere in there reportportal starts to throw exceptions.
https://github.com/user-attachments/assets/020d2f3f-8a0f-4543-86dc-b85a24f08128

**Comment by Pink-Bumblebee** [comment]
Closing this issue as issuer opened more explained version here: https://github.com/reportportal/agent-js-playwright/issues/160
