### ISSUE TITLE
Value is not allowed for field 'status'

### ISSUE THREAD

**Issue by GhsVilela** [reportportal/agent-js-playwright#26]
Hi, 
I'm having problems using the agent, could you guys help me?

This message is appearing after i finish my execution
```json
{
  errorCode: 4001,
  message: "Incorrect Request. [Value is not allowed for field 'status'.] "
}
{
  errorCode: 4001,
  message: "Incorrect Request. [Value is not allowed for field 'status'.] "
}
```
I'm using jest, everything is being sent correctly to report portal but the suit execution doesn't stop automatically

**Comment by AmsterGet** [comment]
@anastasiyamazheika there is was an option with transfering issue)
Could you please share more details about the issue you are facing? Logs and agent configuration details will help us to understand the defect.

**Comment by anastasiyamazheika** [comment]
@AmsterGet, no worries. 
So I just started reporting to Report Portal that's used on our side and send results to it. Results appear but I'm not sure why do I get these errors.
We use build: 5.6.0. 

Part of playwright config:

```
const RPconfig = {
  token: "token",
  endpoint: "endpoint",
  project: "project",
  launch: "Regression",
  attributes: [
    {
      key: "agent",
      value: "playwright"
    }
  ],
  description: "Regression"
};

const config = {
  reporter: [
    ["line"],
    ["@reportportal/agent-js-playwright", RPconfig],
    ["html", { open: "never" }]
  ],
  projects: [
    {
      name: "Chrome Stable",
      use: {
        browserName: "chromium",
        channel: "chrome",
        baseURL: "http://localhost:8080",
        screenshot: "only-on-failure",
        video: "retain-on-failure",
        trace: "retain-on-failure",
        ignoreHTTPSErrors: true,
        launchOptions: {
          args: ["-–allow-file-access-from-files"]
        }
      },
      timeout: 60000
    }
  ]
};

module.exports = config;

```
At the end of tests execution I see:

```
Error: Request failed with status code 400: {"errorCode":4001,"message":"Incorrect Request. [Value is not allowed for field 'status'.] "}
    at /node_modules/@reportportal/client-javascript/lib/rest.js:37:15
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Failed to finish test. Error: Request failed with status code 400: {"errorCode":4001,"message":"Incorrect Request. [Value is not allowed for field 'status'.] "}
    at /node_modules/@reportportal/client-javascript/lib/rest.js:37:15
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Error: Request failed with status code 400: {"errorCode":4001,"message":"Incorrect Request. [Value is not allowed for field 'status'.] "}
    at /node_modules/@reportportal/client-javascript/lib/rest.js:37:15
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Failed to finish test. Error: Request failed with status code 400: {"errorCode":4001,"message":"Incorrect Request. [Value is not allowed for field 'status'.] "}
    at /node_modules/@reportportal/client-javascript/lib/rest.js:37:15
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by AmsterGet** [comment]
@anastasiyamazheika Thank you for the fast response.
Did you set the status manually via the `Reporting API`? If not, I'm guessing the problem is caused by a bug in mapping the `timedOut` playwright status to RP statuses. Did you get a timeout error during a test run?

**Comment by anastasiyamazheika** [comment]
@AmsterGet 
> Did you set the status manually via the ReportingAPI? 
Nope. I don't set anything manually right now :) 

> Did you get a timeout error during a test run?
Nope, there're some tests that just fail because of logic inside.

**Comment by AmsterGet** [comment]
Hello @anastasiyamazheika !
We've recently released a new [5.0.2](https://www.npmjs.com/package/@reportportal/agent-js-playwright) version with a bugfix.
Could you try and give us feedback on this issue?

**Comment by anastasiyamazheika** [comment]
Hello @AmsterGet, great! Thanks a lot! I'm not sure that it will be really soon as our instance is used across the whole company but I will let you know! :) 
Thanks for fixing it!

**Comment by AmsterGet** [comment]
Hello @anastasiyamazheika !
Is it works with the 5.0.2+? Can we close this issue?

**Comment by AmsterGet** [comment]
I'll close the issue since fixes have been released.
Feel free to reopen it if the issue still exists.
