### ISSUE TITLE
[Question] Add test steps to the report

### ISSUE THREAD

**Issue by MichalFidor** [reportportal/agent-js-playwright#32]
Hey,

I'm really excited that there is an official agent to the Playwright test runner. I'm integrating it now into my project and I'm wondering about one thing. Is it possible to attach the logs from test steps as it is done in the default HTML reporter of Playwright? That we don't need to add separate `ReportingApi logs` or `console.logs` in the code but still have it in the report (using the logs which are generated by default in Playwright test runner)? Like on this screen below (needed to hide paths and locators).

![Screenshot 2022-02-25 at 11 47 57](https://user-images.githubusercontent.com/42964298/155703141-c52472fa-cd87-4335-8288-e52fd41e50fe.png)

**Comment by AmsterGet** [comment]
Hello @MichalFidor !
We are currently working on this feature. But PR is still in [draft](https://github.com/reportportal/agent-js-playwright/pull/33).
Such logs will show up as nested steps on the RP side at the log level.

**Comment by MichalFidor** [comment]
Cool, thanks @AmsterGet for the information. Can't wait to see it merged 🤩

**Comment by oranje322** [comment]
Hello @MichalFidor ,
This feature has been released in version 5.0.3 https://github.com/reportportal/agent-js-playwright/pull/40
