### ISSUE TITLE
"Failed to finish test. Error: timeout of 30000ms exceeded." and "Cannot set properties of undefined (setting 'realId')

### ISSUE THREAD

**Issue by MichalFidor** [reportportal/agent-js-playwright#51]
Hi,

On the newest version of agent-js-playwright (5.0.4) and @playwright/test@1.22.2 following errors are thrown during execution:
![error2](https://user-images.githubusercontent.com/42964298/172590994-32cefdea-0370-4c62-9af6-18f4eca59d8e.png)
![errors](https://user-images.githubusercontent.com/42964298/172591006-74c8f0f2-eded-44c0-9337-2cba0e4c2baf.png)

In both cases - with `'includeTestSteps': true,` and without it...

**Comment by AmsterGet** [comment]
Hello @MichalFidor !
As I understand the timeout error breaks the item creation and leads to another error that you mentioned
> Cannot set properties of undefined (setting 'realId')
Such timeout error can be thrown due to ours rest client default timeout 30*1000ms for requests (see [client-javascript](https://github.com/reportportal/client-javascript#timeout-30000ms-on-axios-requests).
Please try to follow the configuration guide and increase the timeout or turn off it if you like.
Let me know if this helps you!

**Comment by MichalFidor** [comment]
I've extended this time and in deed these errors are not longer visible in the console. But it's not the end of this issue, cause while the tests ends on the CI or my local computer - on RP the build is still running and waiting for the action to be completed. Most of the time, one particular action from Playwright itself. I need to force finish the job...

**Comment by AmsterGet** [comment]
@MichalFidor 
It would be nice if you could create a constantly reproducible sample with this issue.
Looking forward for your reply.

**Comment by tr1ble** [comment]
> Hi,
> 
> On the newest version of agent-js-playwright (5.0.4) and @playwright/test@1.22.2 following errors are thrown during execution: ![error2](https://user-images.githubusercontent.com/42964298/172590994-32cefdea-0370-4c62-9af6-18f4eca59d8e.png) ![errors](https://user-images.githubusercontent.com/42964298/172591006-74c8f0f2-eded-44c0-9337-2cba0e4c2baf.png)
> 
> In both cases - with `'includeTestSteps': true,` and without it...

Hello @MichalFidor !
Couldn't reproduce the bug with same steps. Can you give more more details or reproducible sample ?

**Comment by MichalFidor** [comment]
Sorry guys, I was on holidays and a lot of different things were around my head. Anyway, on the newest released version it looks okay!

There is another issue, which starts to appear in case where test runs in two pages in scope of one test. This is the output:

```
1663Failed to start nested step. Error: Launch "1xh68437ccl88su7uq" is already finished, you can not add an item to it
1664    at RPClient.startTestItem (/home/travis/build/node_modules/@reportportal/client-javascript/lib/report-portal-client.js:410:19)
1665    at RPReporter.onStepBegin (/home/travis/build/node_modules/@reportportal/agent-js-playwright/src/reporter.ts:396:45)
1666    at /home/travis/build/node_modules/@playwright/test/lib/reporters/multiplexer.js:101:121
1667    at wrap (/home/travis/build/node_modules/@playwright/test/lib/reporters/multiplexer.js:119:5)
1668    at Multiplexer.onStepBegin (/home/travis/build/node_modules/@playwright/test/lib/reporters/multiplexer.js:98:45)
1669    at Worker.onStepBegin (/home/travis/build/node_modules/@playwright/test/lib/dispatcher.js:279:159)
1670    at Worker.emit (events.js:315:20)
1671    at ChildProcess.<anonymous> (/home/travis/build/node_modules/@playwright/test/lib/dispatcher.js:633:12)
1672    at ChildProcess.emit (events.js:315:20)
1673    at emit (internal/child_process.js:903:12)
1674    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

 But I'll need to investigate it and I'll maybe open another issue on GH if I'll manage to do some reproducible sample

**Comment by PodarDelia** [comment]
> Sorry guys, I was on holidays and a lot of different things were around my head. Anyway, on the newest released version it looks okay!
> 
> There is another issue, which starts to appear in case where test runs in two pages in scope of one test. This is the output:
> 
> ```
> 1663Failed to start nested step. Error: Launch "1xh68437ccl88su7uq" is already finished, you can not add an item to it
> 1664    at RPClient.startTestItem (/home/travis/build/node_modules/@reportportal/client-javascript/lib/report-portal-client.js:410:19)
> 1665    at RPReporter.onStepBegin (/home/travis/build/node_modules/@reportportal/agent-js-playwright/src/reporter.ts:396:45)
> 1666    at /home/travis/build/node_modules/@playwright/test/lib/reporters/multiplexer.js:101:121
> 1667    at wrap (/home/travis/build/node_modules/@playwright/test/lib/reporters/multiplexer.js:119:5)
> 1668    at Multiplexer.onStepBegin (/home/travis/build/node_modules/@playwright/test/lib/reporters/multiplexer.js:98:45)
> 1669    at Worker.onStepBegin (/home/travis/build/node_modules/@playwright/test/lib/dispatcher.js:279:159)
> 1670    at Worker.emit (events.js:315:20)
> 1671    at ChildProcess.<anonymous> (/home/travis/build/node_modules/@playwright/test/lib/dispatcher.js:633:12)
> 1672    at ChildProcess.emit (events.js:315:20)
> 1673    at emit (internal/child_process.js:903:12)
> 1674    at processTicksAndRejections (internal/process/task_queues.js:81:21)
> ```
> 
> But I'll need to investigate it and I'll maybe open another issue on GH if I'll manage to do some reproducible sample

@MichalFidor did you find the solution for this problem?

**Comment by MichalFidor** [comment]
@PodarDelia I didn't. In newest versions of Playwright and RP client I don't have this issue anymore
