### ISSUE TITLE
Parallel Execution : Log goes to wrong test

### ISSUE THREAD

**Issue by shiva4983** [reportportal/agent-js-playwright#69]
Hi Team,

When I do parallel execution with multiple projects. Logs are captured at the wrong test, if I try to add attachments to the log across multiple tests, It all gets added to a single test.

Please provide me a solution.

**Comment by AmsterGet** [comment]
Hello @shiva4983 !
What API are you using to report logs and attachments? I mean [testInfo.attachments](https://github.com/reportportal/agent-js-playwright#attachments) and [console.log](https://github.com/reportportal/agent-js-playwright#logging) or [ReportingAPI](https://github.com/reportportal/agent-js-playwright#reporting-api)?

**Comment by shiva4983** [comment]
Hi @AmsterGet , I am using ReportingAPI..

**Comment by AmsterGet** [comment]
Hi @shiva4983 !
I've released the version 5.0.8 with fixes that might help you. Please try it out.

**Comment by AmsterGet** [comment]
Hi @shiva4983 !
Have you had a chance to try the latest version?

**Comment by AmsterGet** [comment]
@shiva4983 
I will close the issue. Feel free to reopen it if you run into a problem again.
