### ISSUE TITLE
Report portal integration with Accessibility 

### ISSUE THREAD

**Issue by AnanthaNagaraj** [reportportal/agent-js-playwright#76]
Created Test script and integrated  with **Report portal** and **accessibility**. 

When i add '**includeTestSteps: "true"** under **RPconfig**, and execute test case. Test execution completed but when I look  into results under Report portal, accessibility step will be **"IN_PROGRESS"** state
**page.evaluate  IN_PROGRESS** 

**Config File :** 
`const RPconfig = {
  token: "0000000-74ba-4c75-0000-dummy",
  endpoint: "https://reportportal.dummy/api/v1",
  project: "SampleProjectTemplate",
  launch: "Demo-2023",
  includeTestSteps: "true",
  attributes: [
    {
      key: "key",
      value: "value",
    },
    {
      value: "value",
    },
  ],
  description: "Test Play wright",
};`

**Screen shot :** 
![image](https://user-images.githubusercontent.com/84306116/211738337-f37292f7-d3f2-42cb-8ff2-a106223958e0.png)

HTML Report :
![image](https://user-images.githubusercontent.com/84306116/211743058-eb581261-c22e-44da-8b94-9e21dd7e8c56.png)

**NOTE :** 
1. If **includeTestSteps: "true"** is not added in config file then IN_PROGRESS not found.
2. **Report from Report Portal : with out includeTestSteps parameter**
![image](https://user-images.githubusercontent.com/84306116/211739444-d95d385f-1ebf-46f0-a2af-98106d241597.png)
3. HTML Report :
![image](https://user-images.githubusercontent.com/84306116/211743258-8c17224c-8686-4953-917f-9111bdf39bb1.png)

//===============
Script : 
import { test, expect } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";

test.only("a11y test", async ({ page }, testInfo) => {
  await page.goto("http://zero.webappsecurity.com/");
  console.log("Title :: " + (await page.title()));

  const axe = await new AxeBuilder({ page }).setLegacyMode();
  const results = await axe.analyze(); // 4
  await testInfo.attach("Test", {
    body: JSON.stringify(results, null, 2),
    contentType: "application/json",
  });

  await page.click("#signin_button");

  // Click on Sign In button
  await page.click("text=Sign in");
  console.log("Sign IN :: " + (await page.title()));
  const error_msg = page.locator(".alert alert-error");
});

**Comment by gabriel-finch-kr** [comment]
I experienced a very similar result. Setting `includeTestSteps: true` my Playwright tests would finish and Playwright HTML report would report that all steps were completed, but RP indicated some (50%) steps were still In-Progress.

**Comment by AndriiFrolov** [comment]
same for me, but nothing related with accessibility. Just when I set includeTestSteps: true - launch in RP never finishes. 
version 5.0.11

**Comment by danielsobon** [comment]
Same for me, especially on bigger test suites
I have even report portal located on the same virtual machine as playwright runner
No errors in console logs related to reportportal status items update
![image](https://user-images.githubusercontent.com/114917701/233698486-faf1d2c8-cf74-4300-b23e-79a173ee29da.png)

**Comment by AmsterGet** [comment]
Hello guys!
This seems to be related to the handling of the Playwright's steps on the agent's side.
I'll try to reproduce and debug this issue and notify you here.

**Comment by Bam6ycha** [comment]
Hi there @danielsobon @AndriiFrolov @gabriel-finch-kr @AnanthaNagaraj 
I hope you are all doing well!
This issue was fixed. You can try it out in the new agent version.
Thank you all for participating! Best regards!

**Comment by AndriiFrolov** [comment]
@Bam6ycha seems fixed, but why I see 'nested' messages not in the step? is it expected?
Example:
    await test.step(`WHEN valid credentials are used`, async () => {
      await loginPage.login(process.env.USER_FOR_TESTS!, process.env.USER_FOR_TESTS_PASSWORD!);
    });
step calls this method:

  public async login(username: string, password: string): Promise<void> {
    console.log(`Attemting to login with credentials page ${username}, ${password}`);
    ...
  }
what I see on RP:
<img width="556" alt="image" src="https://github.com/reportportal/agent-js-playwright/assets/19844745/c9905c28-aa57-46c4-941c-738ac6ec287f">
I expect this message to be inside 'WHEN valid credentials are used' step so that I see it only when expand step

**Comment by AmsterGet** [comment]
Hey @AndriiFrolov !
I've created a ticket in the [Playwright](https://github.com/microsoft/playwright/issues/23810) repo.
Feel free to 'thumb' it up to highlight interest from community for Playwright core team.
