### ISSUE TITLE
Add enable in Playwright config

### ISSUE THREAD

**Issue by MihirModiAC** [reportportal/agent-js-playwright#78]
Is it possible to add an enable=true|false argument in RPConfig of the playwright, like we have rp.enable in Java?

**Comment by AmsterGet** [comment]
Hello @MihirModiAC !
Is it possible to control it outside of the reporter?

I mean smth like this:
```javascript
const isRPEnabled = process.env.RP_ENABLED;

const config: PlaywrightTestConfig = {
  reporter: [['line']].concat(isRPEnabled ? ['@reportportal/agent-js-playwright', RPconfig] : []),
};
```

And in this case, no instance of the reporter will be created.

**Comment by MihirModiAC** [comment]
Yes, I think this is what I am looking for. Let me give it a try. Thank you.

**Comment by MihirModiAC** [comment]
I only want to update results for some runs not all of them. If I update playwright.config.ts as mentioned, the results will be updated all the time. In the Java Properties file, we have rp.enable=true or false which can dynamically control the reporting. I can set rp.enable=false in the command line and it will skip reporting. I tried your suggestion but it does not work. The playwright does not allow me to concat anything to the reporter, giving me a syntax error.

**Comment by AmsterGet** [comment]
It was just a tip, looks like you've got a TS error with types mismatch, this can be fixed:

```javascript
import { PlaywrightTestConfig, ReporterDescription } from '@playwright/test';

const isRPEnabled = process.env.RP_ENABLED;

const config: PlaywrightTestConfig = {
  reporter: isRPEnabled ? [['line'], ['@reportportal/agent-js-playwright', RPconfig]] : [['line']],
};

// OR

const reporterList: ReporterDescription[] = [['line']];

if (isRPEnabled) {
  reporterList.push(['@reportportal/agent-js-playwright', RPconfig]);
}

const config: PlaywrightTestConfig = {
  reporter: reporterList,
};
```

**Comment by MihirModiAC** [comment]
Yes, this worked. Thank you. Please close the ticket. Appreciate your help.
