### ISSUE TITLE
testInfo.fail() adding same test twice.

### ISSUE THREAD

**Issue by quldude** [reportportal/agent-js-playwright#79]
`testInfo.fail();` is adding the same test twice in ReportPortal and marking both as test passed instead of having 1 test with fail status.

**Comment by AmsterGet** [comment]
Hello @quldude !
I've just released the new version 5.0.9 with some fixes related the issue you've mentioned.
Could you please try and confirm that the issue no longer exists?

**Comment by AmsterGet** [comment]
Hello @quldude !
Hope you are doing well.
I'll close the issue.
Feel free to contact us or reopen it if necessary.
