### ISSUE TITLE
Playwright TestRunner Compatibility

### ISSUE THREAD

**Issue by committedtester** [reportportal/agent-js-playwright#8]
Gday! Great to see that Playwright compatibility is being considered. 
I've noticed this repository is based on jest, but Playwright now has it's own test runner (which wraps around Jest)
Are there any plans to support this? 

https://playwright.dev/docs/test-reporters
They've made the start towards Allure, but I do prefer ReportPortal!

**Comment by AmsterGet** [comment]
Guys, I'll close this issue. Feel free to open other issues if you have any questions.
