### ISSUE TITLE
Few tests are marked as interrupted in RP launch but actually passed

### ISSUE THREAD

**Issue by andriyyarish** [reportportal/agent-js-playwright#97]
Hello.
Have an issue with few tests which are always marked as interrupted.

Two of them are always interrupted on the step that contains
await **expect.sof**t(monitor.something.frame)
          .toHaveScreenshot(element + '.png', { threshold: 0.2, maxDiffPixelRatio: 0.2 });

and another one **on afterAll**
test.afterAll(async ({ someApi }) => {
    const bookmarks: string[] = Object.values(data).filter(
      (value) => value != data.bookmarkDelete && value != data.bookmarkEdit,
    );
    await Promise.all(bookmarks.map((bookmarkName) => someApi.deleteBookmarkByName(bookmarkName)));
  });

Does anybody face something similar?

**Comment by andriyyarish** [comment]
"@playwright/test": "1.31.0",  "@reportportal/agent-js-playwright": "5.0.11". I will try to find a time and prepare a sample.

**Comment by duartmig** [comment]
Hello, facing same issue with

const elementScreenshot = await page.getByTestId(locators).screenshot();

expect(elementScreenshot).toMatchSnapshot('image.png'); <- ininterrupted in report portal here

**Comment by AmsterGet** [comment]
Hello @duartmig !
What status does Playwright runner give in your case?

**Comment by duartmig** [comment]
Hello @AmsterGet , they are passed. 
I also tried to execute the tests locally and export results to report portal and all good, my issue is when I run them from CD. On jenkins I have my tests all passed (including these visual tests) but then on report portal, all the tests that call toMatchSnapshot() method are as ininterrupted.

**Comment by AmsterGet** [comment]
From reportportal agent side we mark tests as `interrupted` only in case the [TestCase outcome](https://playwright.dev/docs/api/class-testcase#test-case-outcome) is `skipped` and [TestResult status](https://playwright.dev/docs/api/class-testresult#test-result-status) is `interrupted`.
I'll try to reproduce this issue, but it would be helpful if you could prepare a small reproducible suite with tests.

**Comment by duartmig** [comment]
Hello @AmsterGet , sorry, I think I was not clear.
The status for that step is interrupted because I need to force finish in RP (tests are failed due to this) but what happens is that this specific step `expect(elementScreenshot).toMatchSnapshot('image.png');` is forever IN PROGRESS even if subsequent steps are passed or failed. This only happens when tests run on CD and on jenkins, the report is OK with all tests successfully executed.
Do you recommend any workaround?

**Comment by Bam6ycha** [comment]
Hi there @andriyyarish @duartmig 
I hope you are all doing well!
This issue was fixed. You can try it out in the new agent version.
Thank you all for participating! Best regards!
